version: "3"
services:
  backend:
    build: ./backend/
    restart: always
    command: "python3 ./run_server.py"
    ports:
      - 8000:5000
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    build: ./database/
    restart: always
    environment:
      MYSQL_DATABASE: 'games_db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
