version: "3"
services:
  frontend:
    stdin_open: true
    build: ./frontend/
    container_name: game_recommendation_frontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend
    links:
      - backend
    tty: true

  backend:
    build: ./backend/
    container_name: game_recommendation_backend
    restart: always
    command: "python3 ./run_server.py"
    ports:
      - 8000:5000
    links:
      - mysql
    depends_on:
      mysql:
        condition: "service_healthy"

  mysql:
    build: ./database/
    container_name: game_recommendation_database
    restart: always
    environment:
      MYSQL_DATABASE: 'games_db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "curl", "-f", "http://mysql:3306"]
      timeout: 10s
      retries: 60